services:
  web:
    build: .
    container_name: sns
    command:
      - bash
      - -c
      - |
        python manage.py migrate --settings=SNS.settings.prod
        python manage.py runserver 0.0.0.0:8000 --settings=SNS.settings.prod
    volumes:
      - ./:/app/server/sns/
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 81:81
    depends_on:
      - web