# Generated by Django 4.0.6 on 2022-07-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그 이름')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그들',
                'db_table': 'tag',
                'ordering': ['-id'],
            },
        ),
    ]
